services:
  db:
    container_name: orders-db
    image: postgres:11.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server:
    container_name: orders-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - DB_MIGRATION_PATH=/migrations
    volumes:
      - ./configs/local.template.env:/.env:ro
      - ./internal/infra/database/psql/migrations:/migrations:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
