version: '3'

services:
  db:
    container_name: orders-db
    image: postgres:11.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - ./internal/infra/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  #rabbitmq:
  #  image: rabbitmq:3-management
  #  container_name: rabbitmq
  #  restart: always
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"
  #  environment:
  #    RABBITMQ_DEFAULT_USER: guest
  #    RABBITMQ_DEFAULT_PASS: guest
